/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    PrintPreview: typeof import('./components/sword_weirdos/PrintPreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwordWeirdoMainWindow: typeof import('./components/sword_weirdos/SwordWeirdoMainWindow.vue')['default']
    SwordWeirdosRepoDialogue: typeof import('./components/sword_weirdos/SwordWeirdosRepoDialogue.vue')['default']
    WarbandConfig: typeof import('./components/sword_weirdos/WarbandConfig.vue')['default']
    WarbandEntityClassPicker: typeof import('./components/sword_weirdos/WarbandEntityClassPicker.vue')['default']
    WarbandEntityCofiguration: typeof import('./components/sword_weirdos/WarbandEntityCofiguration.vue')['default']
    WarbandEntityList: typeof import('./components/sword_weirdos/WarbandEntityList.vue')['default']
    WarbandEntityPreview: typeof import('./components/sword_weirdos/WarbandEntityPreview.vue')['default']
    WarbandEntitySpellPicker: typeof import('./components/sword_weirdos/WarbandEntitySpellPicker.vue')['default']
    WarbandEntityStatPicker: typeof import('./components/sword_weirdos/WarbandEntityStatPicker.vue')['default']
    WarbandEntityWeaponPicker: typeof import('./components/sword_weirdos/WarbandEntityWeaponPicker.vue')['default']
  }
}
